[build]
builder = "nixpacks"

[build.env]
PHP_VERSION = "8.4"

[build.nixpacksConfig]
[build.nixpacksConfig.phases.setup]
nixPkgs = ['php84', 'php84Packages.composer', 'php84Extensions.pdo_mysql', 'php84Extensions.mysqli']

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"